name: CI

on: [push, pull_request]
env:
  XCODE_VER: 12.4

jobs:
  build:
    strategy:
      matrix:
        xcode_version: ['12.4']
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app
    steps:
      - name: Check out Satin 
        uses: actions/checkout@v2
      - name: Build Satin 
        run: |
          set -euo pipefail
          swift build
